import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";

const DmSans = DM_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${DmSans} antialiased max-w-full`}
      >
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
